version: '3.8'

services:
  postgres-auth:
    image: postgres:15
    container_name: postgresmicroeco
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: microecodb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-net

volumes:
  postgres_data:

networks:
  microservice-net:
    driver: bridge
